# Build stage
FROM node:18-alpine as builder

WORKDIR /app

COPY package.backend.json package.json
COPY tsconfig.json .

RUN npm install

COPY src ./src

RUN npm run build

# Production stage
FROM node:18-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package.backend.json package.json
COPY package-lock.json .

RUN npm install --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["npm", "start"]
